### ISSUE TITLE
User Roles in Apollo Studio - Lock down API keys

### ISSUE THREAD

**Issue by michael-watson** [apollographql/apollo-studio-community#10]
As an admin of Apollo Studio, I want to be able to lock down my api keys so that I can have only 1 api key with write permissions to that specific graph variant. Use case is around locking down specific api keys for each environment (dev/test/prod) and those api keys should only have write access to the associated graph variant.

**Comment by tvvignesh** [comment]
Hi. I had raised this already here: https://github.com/apollographql/apollo-server/issues/3734 and had also sent a note to the support team. Looks like this is on their radar and they are working on it.

**Comment by daniman** [comment]
We've outlined a plan that will give a lot more control to API keys for graphs by allowing you to both set a role for those keys, and set certain variants as protected that we'd love to get your feedback on: https://github.com/apollographql/apollo-studio-community/blob/main/preview-docs/GraphRoles.md

**Comment by setchy** [comment]
Today is the day 🎉

**Comment by setchy** [comment]
Really liking the updates @daniman.  The new roles for users and API Keys is great, protected variants and graph visibility are all much welcome at my organization. 

It'd be great if in a future enhancement we could also assign a graph variant to an API Key, so that we can have separate API Keys dedicated for each variant (or environment as our use-case is).  We use this practice for our secret-based tokens

**Comment by daniman** [comment]
Woohoo, glad you've enjoyed the updates @setchy! I definitely agree about having API keys match to variants in the future, but we can make a new ticket for that. I'm going to close this one for now.

For reference, Graph Roles, Protected Variants, and Roles for Graph API keys are all now available in Studio Enterprise: https://www.apollographql.com/blog/graphql-roles-and-protected-variants/

**Comment by setchy** [comment]
@daniman isn't the original issue / feature request still unresolved though? https://github.com/apollographql/apollo-studio-community/issues/10#issue-664518162

**Comment by setchy** [comment]
Raise #53
