### ISSUE TITLE
Notifications:  Include graph variant name in performance alerts

### ISSUE THREAD

**Issue by setchy** [apollographql/apollo-studio-community#110]
### Current behavior
Whenever a `Performance Alert` notification is delivered to Slack, the footer of this notification contains a row with the following information/convention

`Service: {graphName} | {month} {date}`

This makes it tricky to triage which variant the performance alert was for triggered for when using a shared slack channel (ie: a squad channel)

### Enhancement proposal
Update the above convention to include the variant name / [GRAPH_REF](https://www.apollographql.com/docs/rover/conventions/#graph-refs)) for which the performance alert exceeded the configured thresholds - ie: `{graphName}@{variantName}`

**Comment by timbotnik** [comment]
@setchy this seems like a quick change - we're going to have a look.

**Comment by setchy** [comment]
Thank you @timbotnik

**Comment by timbotnik** [comment]
We landed a change here that surfaces the graph variant, note that it only works when you include a variant in the configuration for the alert.
