### ISSUE TITLE
Studio is doing IntrospectionQuery to graphql every milliseconds

### ISSUE THREAD

**Issue by ankitjainOfficial** [apollographql/apollo-studio-community#120]
My bandwidth usage increased manifolds from last Thursday.

![image](https://user-images.githubusercontent.com/8897202/141744984-095dbb6a-05b0-4471-aa66-46dc080e45c1.png)

On further diving, I found, that studio is sending IntrospectionQuery every milliseconds, and being a development project, and with multiple studio instances open, this is crashing our servers

<img width="1919" alt="Screenshot 2021-11-15 at 1 39 25 PM" src="https://user-images.githubusercontent.com/8897202/141745396-50649101-3194-401d-81e7-c54a65c31468.png">

Any help would be appreciated.

**Comment by mayakoneval** [comment]
Hey @ankitjainOfficial, thanks for the report. 

The team fixed a similar issue to this last week. Could you try updating your Studio version by clicking on your avatar icon at the top right and then selecting "Update available, click to relaunch" if it is available in the drop down? 

If you are updated and are still seeing this issue, we will investigate. I assume this is happening on Studio Sandbox. It would be helpful if you could please let me know where your endpoint is coming from. For example, is it an AppSync endpoint, or hosted by another service?

<img width="282" alt="Screen Shot 2021-11-15 at 10 34 35 AM" src="https://user-images.githubusercontent.com/14367451/141809528-7688819c-4286-4aeb-905a-213e46e872bc.png">

Thanks

**Comment by dreygos** [comment]
Hello

We are facing the same issue, just checked that the latest version is installed, we have a service hosted in aws served over an https endpoint that we are giving to apollo, along with a bearer token, and the same happens that our endpoint is hit very often and crashing our containers.

Thank you.

**Comment by ankitjainOfficial** [comment]
> Hey @ankitjainOfficial, thanks for the report.
> 
> The team fixed a similar issue to this last week. Could you try updating your Studio version by clicking on your avatar icon at the top right and then selecting "Update available, click to relaunch" if it is available in the drop down? If you are not logged in, you can click the speaker icon in the top right, which will open a modal, and there might be an "Update available, click to relaunch" button in the bottom left if you can update.
> 
> If you are updated and are still seeing this issue, we will investigate. I assume this is happening on Studio Sandbox. It would be helpful if you could please let me know where your endpoint is coming from. For example, is it an AppSync endpoint, or hosted by another service?
> 
> <img alt="Screen Shot 2021-11-15 at 10 34 35 AM" width="282" src="https://user-images.githubusercontent.com/14367451/141809528-7688819c-4286-4aeb-905a-213e46e872bc.png">
> 
> <img alt="Screen Shot 2021-11-15 at 10 41 05 AM" width="546" src="https://user-images.githubusercontent.com/14367451/141810529-9bee9b8f-709e-4b30-8052-72a324794516.png">
> 
> Thanks


I'm on version d1de14


I just updated as per your suggestion, and the issue still seems to persist.

**Comment by ankitjainOfficial** [comment]
Also, the graphql is my own service.

**Comment by mayakoneval** [comment]
Thanks for the info, @ankitjainOfficial & @dreygos,

A couple questions: If you go to your [connection settings](https://studio.apollographql.com/sandbox/explorer?overlay=connection-settings) and uncheck the 'Auto Update' option, do the requests from Studio continue? Are the requests happening 1/second, or is it more frequently?

**Comment by ankitjainOfficial** [comment]
Yes, network request is continues. And I think, the interval is more than 1 per second. 

Also, I'm not in sandbox. Here is how my URL looks: https://studio.apollographql.com/graph/My-Graph-4-dc7rar/explorer?variant=current, if it helps.

**Comment by dreygos** [comment]
same here as in @ankitjainOfficial 's case

**Comment by mayakoneval** [comment]
@ankitjainOfficial, @dreygos the fix should be out now! Please update you studio version and let me know if you see anything fishy 🐟. Thanks again for the report!
