### ISSUE TITLE
Introspection query should include custom headers

### ISSUE THREAD

**Issue by dburles** [apollographql/apollo-studio-community#122]
My server is setup to respond to an introspection query in the presence of an `introspection` header along with a token, however, it seems that custom headers aren't included in Apollo Studio's introspection query.

**Comment by cheapsteak** [comment]
Hi there

We don't currently send all headers for the tab along with the introspection request

For now, please set the headers you'd like to send in introspection requests in the default headers section 🙏 

![image](https://user-images.githubusercontent.com/743976/143945484-cdf70ef8-0415-41ee-a4b9-90d3ffe7d4fc.png)

![image](https://user-images.githubusercontent.com/743976/143945514-eca282cf-7f77-4743-b21e-5f64bcedc9d1.png)

**Comment by dburles** [comment]
That works perfectly! Thanks @cheapsteak!
