### ISSUE TITLE
Make studio "include cookies" by default

### ISSUE THREAD

**Issue by uripre** [apollographql/apollo-studio-community#125]
Hi! 

I'm looking for a way to make the studio enable "Connection settings" -> "Include cookies" by default. Is there any way I can configure ApolloServer that way?

I'm using the local variant of the studio with introspection in production, along with jwt token verification via express middleware. That way only my authenticated clients can view the studio, but they currently need to manually enable the above in order to make it work.

Thanks!

**Comment by cheapsteak** [comment]
Hi there
That's a very reasonable request
We don't support this yet, will add it to our list

**Comment by branchvincent** [comment]
we have this exact use-case as well, would be much appreciated!

**Comment by cheapsteak** [comment]
This should be available on the recent version of apollo-server!  
https://github.com/apollographql/apollo-server/pull/6014

**Comment by uripre** [comment]
> This should be available on the recent version of apollo-server! [apollographql/apollo-server#6014](https://github.com/apollographql/apollo-server/pull/6014)

Amazing !!
