### ISSUE TITLE
Support for block (multi-line) strings in Apollo Studio UI

### ISSUE THREAD

**Issue by mgagliardo91** [apollographql/apollo-studio-community#131]
A feature that is supported by GraphQL and working in the old Apollo GraphQL Community Playground/ OSS GraphIQL does not appear to be supported from the Apollo Studio UI - block strings `"""`.

For example, the following mutation:

```graphql
mutation {
  sendMessage(payload:"""
  This is a multi-line
  string that will get parsed and 
  formatted correctly with new-line chars.
  """) {
    result
  }
}
```

When passing a query such as this using Apollo Studio UI, I am receiving a client-side GraphQLError complaining about the formatting and indicating a bad request do to the quotes (it sees each pair of quotes as a separate string). Is this something that could be prioritized to be fixed? We will have to drop back to the playground temporarily to support this, but we much prefer the studio UI (awesome job by the way!).

Thanks!

**Comment by papollosc** [comment]
Hi @mgagliardo91! Thank you so much for raising this. We have noted your request and will keep you updated on the progress.

**Comment by mgagliardo91** [comment]
> Hi @mgagliardo91! Thank you so much for raising this. We have noted your request and will keep you updated on the progress.

@papollosc thanks for the reply! Looking forward to seeing the update.

**Comment by jgzuke** [comment]
This should be fixed 🎉 If its not working, make sure you're on the latest version of Studio by clicking on the 📣 in the top right corner
