### ISSUE TITLE
Question: how to fill field description ?

### ISSUE THREAD

**Issue by jsomsanith-tlnd** [apollographql/apollo-studio-community#134]
In Apollo explorer, I see in the `documentation` tab a description with `No description.` in it.

![image](https://user-images.githubusercontent.com/10761073/148948513-6814f169-df0c-46c2-856d-6cf48e2a1eef.png)

I can't find any doc telling how we can write them.
I tried adding comments in the schema, but it doesn't take it into account.

How can I specify them ?
(Thank you for your hard work, the product is awesome)

**Comment by glasser** [comment]
You write documentation as strings (typically with the triple-coded block string syntax) in front of the field definition.  (In very old versions of GraphQL before this feature existed, you could write them as comments, and it's possible there are still tools and docs out there that encourage this.) See https://www.apollographql.com/docs/apollo-server/schema/schema/#descriptions-docstrings for more details!

**Comment by jsomsanith-tlnd** [comment]
Didn't know the community website.
Sorry for posting the issue here, and thank you for your answer ! Gonna try this :)
