### ISSUE TITLE
Feature request: batch copy/paste multiple headers in Explorer

### ISSUE THREAD

**Issue by flobories** [apollographql/apollo-studio-community#135]
Hello Apollo Studio Team,

I would like to suggest a small quality of life improvement to the Studio Explorer.
I often find myself copying headers between different browser profiles and environments, and I wish there was a way to **copy and paste multiple headers at the same time**.

Today, I have to manually insert my three standard headers and navigate across the six field generated to copy paste values individually.

![image](https://user-images.githubusercontent.com/7430239/151225479-3db1a770-3142-4043-b7cb-35363badf566.png)

I couldn't find a similar issue filed here, and I hope you find this very nit feedback valuable. Thank you for all the great tools!

**Comment by mayakoneval** [comment]
Hey! Thanks for the suggestion. 

We have created a ticket to be able to support copy & pasting multiple headers.

**Default headers** might be helpful to you as well.  Default headers are tied to a variant and are applied to every workspace by default. You can edit your default headers for a graph through the connection settings.
<img width="492" alt="Screen Shot 2022-01-28 at 11 27 01 AM" src="https://user-images.githubusercontent.com/14367451/151609232-e7d63dfe-9dac-43dd-9ad3-94e5fdaf9459.png">

Thanks

**Comment by flobories** [comment]
Thank you for the suggestion of default headers @mayakoneval ! This will save me a few steps.

**Comment by papollosc** [comment]
Hi @flobories We have added the ability to bulk add headers in Explorer. https://github.com/apollographql/apollo-studio-community/blob/main/CHANGELOG.md#2022-08-29 Hopefully, this helps and makes it easier to copy/paste headers. Will close this feature request.

**Comment by flobories** [comment]
Awesome, thank you @papollosc !
