### ISSUE TITLE
"We've run into an unexpected error."

### ISSUE THREAD

**Issue by lr-mjaouen** [apollographql/apollo-studio-community#14]
Hi,

Very very frequently I have this issue:
![image](https://user-images.githubusercontent.com/56837954/90282229-fa2e5a80-de3b-11ea-99c4-56f6d413ca6d.png)

With those logs (It seems to be related to datadog? I don't have a datadog integration at all):
![image](https://user-images.githubusercontent.com/56837954/90280627-3ad8a480-de39-11ea-95ae-a9c30eda4ff2.png)

Byebye

**Comment by daniman** [comment]
Thanks for reporting @lr-mjaouen! It's a transient error that has become a lot more frequent recently, and we're looking into why that is and how to fix it today and likely next week.

**Comment by lr-mjaouen** [comment]
Thank you!

**Comment by daniman** [comment]
Hey @lr-mjaouen –– we've made a few changes in the last few weeks to make this more stable and haven't seen it since then. I'm going to close this issue for now, but let us know if it comes back? Thanks!

**Comment by lr-mjaouen** [comment]
Ok thank you, I will use it probably next week.
