### ISSUE TITLE
Including cookies seems to have stopped working

### ISSUE THREAD

**Issue by saevarb** [apollographql/apollo-studio-community#168]
Hello.

I have been using apollo studio across several different projects for a few months.

Some of these projects require authentication, and for this reason I've had to do some extra bit of setup during development, to change my auth cookie settings well as set up CORS, as is outlined in apollo studio when you enable "Include cookies". 

This has worked without any issues for months(and very well -- thanks for apollo studio!).

After doing some completely different work for a couple of weeks, I now come back to one of these projects that require authentication, and it seems like using apollo studio to interact with my GQL server has just spontaneously stopped working. No matter what I do, no cookies are ever sent from apollo studio. 

To troubleshoot this, I have:

 - Cleared all cookies and logged back in
 - Tried logging in in incognito mode
 - Tried both Firefox and Chrome
 - Verified that my CORS and cookie settings are correct, both in code as well as in the browser when the cookie has been created
 - Logged the headers for the incoming request to see if cookies are being sent from studio (they are not)
 - Checked out several different older commits up to several months old to ensure no change on our end has caused this

Is there any chance something like #88 has occurred again?

**Comment by William010x** [comment]
Hi @saevarb , sorry to hear to that you have been having issues with the cookies.

Could I ask which package you are using for Apollo Server and what are you using to set up CORS? Maybe there could be something overriding your CORS options. If possible, could you provide a repository that I can clone with reproduction steps?

I have it working for a simple Apollo server using `apollo-server-express` and one using `apollo-server`. Adding these CorsOptions and toggling on "Include cookies" causes introspection and other requests to send cookies (that have `Secured; SameSite=None`)
```
cors: {
    origin: 'https://studio.apollographql.com',
    credentials: false,
},
```

Another thing to potentially try is setting `X-Forwarded-Proto: https` as a Shared Header in the Apollo Sandbox Connection Settings

**Comment by saevarb** [comment]
Hey!

Sorry for the late reply. 

I didn't end up figuring it out right then and there, and ended up having to do some other stuff. But then I ran into the same bug again, in a different project. I ended up fixing it by deleting any and all apollo related cookies I could find.

I spent quite a bit of time verifying all of the settings involved(CORS, cookie settings and so on) and I'm as sure as I can be that they were all correct. I'm using this same configuration in 3 projects. 

I have been using studio across different projects in different configurations, and I'm not sure if there might be a bug somewhere where some cache doesn't get evicted. Either way, I can't reproduce it and now it's gone, so you can just close this issue.

**Comment by William010x** [comment]
No problem, glad to hear that you fixed it and it is working for you know! Apologies for the inconvenience, let us know if the issue ever comes up again.
