### ISSUE TITLE
File upload type not avaliable in variables

### ISSUE THREAD

**Issue by lantos1618** [apollographql/apollo-studio-community#174]
Hi the scalar type file upload is not being detected in the variables box.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/39604275/177048989-5da5e052-2208-42f3-bc11-68c06cfade72.png">

is it just me or has it not been implemented yet in Apollo studio?

**Comment by SebaBoler** [comment]
Have you any plans to do it?  Now FireCamp has that and 2 more.

**Comment by lantos1618** [comment]
> Have you any plans to do it? Now FireCamp has that and 2 more.

I don't think they have the capacity to do this, unfortunately.

@cheapsteak is Apollo open to a short term contract so that I can build this feature? I can help out with this

**Comment by mayakoneval** [comment]
Hi folks, we just released this feature. You should see an 'Add files' button on the Variables tab in Explorer that will let you add files for servers that support the graphql multipart request spec. 

Let me know if something doesn't work as expected 🙏🏻 thanks!

[Changelog entry here](https://github.com/apollographql/apollo-studio-community/commit/d69b485e2433e13e55b56c7ec1604a90496e6136)
