### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by hmz22** [apollographql/apollo-studio-community#177]
When I use ApolloServerPluginLandingPageLocalDefault and use sandbox cant see anything.
I try for [Your client does not have permission to get URL /_latest/embeddable-sandbox.umd.production.min.js](https://embeddable-sandbox.cdn.apollographql.com/_latest/embeddable-sandbox.umd.production.min.js)
show this error
Error: Forbidden
Your client does not have permission to get URL /_latest/embeddable-sandbox.umd.production.min.js from this server.
I use from Iran please unblock 403 error for this location

**Comment by mayakoneval** [comment]
Hi @hmz22! Thanks so much for your issue. Unfortunately, we are currently unable to remove this restriction. 

Thanks, Maya
