### ISSUE TITLE
Add "Authorize" button to support authentication via the UI

### ISSUE THREAD

**Issue by dan-cooke** [apollographql/apollo-studio-community#178]
It would be really useful if we could authenticate with our identity providers via the UI, instead of having to fetch a new token and add it as a header everytime we open the UI.

Especially when sharing the studio with less technical users.

### Proposal
Add some additional options to the `ApolloServerPluginLandingPageLocalDefault()` function.

**OAuth2 example**
```.ts
ApolloServerPluginLandingPageLocalDefault({
    authentication: {
        type: 'oauth',
        options: {
              tokenUrl: '',
              clientId: '',
              clientSecret: ''
         }
    }
})
```

**Comment by setchy** [comment]
We're using preflight scripts and default headers with environment variable placeholders with moderate success to achieve similar

Some example scripting shown in [this blog post](https://www.apollographql.com/blog/announcement/tooling/automatically-authenticate-with-preflight-scripts-in-apollo-studio-explorer/)

Our scripts are something like this (with lots of room for improvement)

```
// OAuth2 Token Server Config
const variant = '@staging'
const OAUTH2_TOKEN_URL = 'https://something.com/oauth/token'
const OAUTH2_AUDIENCE = 'https://something-else.com'


// Environment Variables
const CLIENT_ID = 'clientId'
const CLIENT_SECRET = 'clientSecret'
const TOKEN_EXPIRES_AT = 'tokenExpiresAt'
const TOKEN = 'token'


if (explorer.environment.get(CLIENT_ID) == undefined) {
  const clientId = await explorer.prompt(`Please enter your ${variant} Client ID below`)
  explorer.environment.set(CLIENT_ID, clientId)
}

if (explorer.environment.get(CLIENT_SECRET) == undefined) {
  const clientSecret = await explorer.prompt(`Please enter your ${variant} Client Secret below`)
  explorer.environment.set(CLIENT_SECRET, clientSecret)
}

var dateTime = new Date().getTime();
var tokenExpiresAt = explorer.environment.get(TOKEN_EXPIRES_AT)
if (tokenExpiresAt == null || dateTime > tokenExpiresAt) {

  const response = await explorer.fetch(OAUTH2_TOKEN_URL, {
    method: 'POST',
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ 
        "client_id": explorer.environment.get(CLIENT_ID),
        "client_secret": explorer.environment.get(CLIENT_SECRET),
        "audience": OAUTH2_AUDIENCE,
        "grant_type": "client_credentials"
      }),
  })

  const json = JSON.parse(response.body);
  explorer.environment.set(TOKEN, json.access_token);
  explorer.environment.set(TOKEN_EXPIRES_AT, dateTime + json.expires_in);
}
```

And default headers of `Authorization`: `Bearer {{token}}`

**Comment by dan-cooke** [comment]
@setchy thanks for the example, yeah I ‘client_credentials’ works great for dev testing.

But if you need to log in with a particular user, or your API is accessed by client developers who need to test their particular applications / users. This grant is not ideal.

That is why it would be nice to see it built into the UI.

Im pretty sure GraphiQL allows something similar as the GitHub API allows you to login to your account via OAuth2

**Comment by setchy** [comment]
💯 @dan-cooke - +1 for all the reasons you listed above

**Comment by daniman** [comment]
@dan-cooke we’ve recently released a bunch of different utilities for you to embed the Sandbox and Explorer on your own websites. Not sure if you’d want to take your users away from Studio, but you could embed the Explorer on your own site and then have the parent page handle authentication. I’ve used this to add a “login” button on a parent page that launches as OAuth prompt to fetch a token and then pass it along in Explorer’s requests as a header.

Love your suggestion for Apollo Server changes. The intent with the Embedded Explorer was to give you maximum flexibility on auth while we continue to improve the options in other places as well.

The docs for that are here: https://www.apollographql.com/docs/studio/explorer/embed-explorer

**Comment by dan-cooke** [comment]
@daniman that is awesome! I had no idea you could embed the explorer.

This pretty much solves the issue at hand.

**Comment by papollosc** [comment]
@dan-cooke Here is a walk through of `how to` if needed: https://www.apollographql.com/blog/tooling/graphql-ide/how-to-embed-explorer-for-a-private-graph/ 

Will close this comment for now! Please let us know if you have any other feedback as you try it out :)
