### ISSUE TITLE
Schema check fails when all changes are in one branch

### ISSUE THREAD

**Issue by mozhde-amiri** [apollographql/apollo-studio-community#207]
## Context
Since today, we are facing schema checks failure in cases which it doesn't make sense. 

I added this input and mutation in the same branch:

 ```
input ActivateCardInput {
  cardId: String!
  activationCode: String!
}
extend type Mutation {
  activateCard(input: ActivateCardInput!): Boolean!
}
```
Then I got this validation error:
```
│ FAIL   │ REQUIRED_FIELD_ADDED_TO_INPUT_OBJECT │ input type `ActivateCardInput`: required field `cardId` added         │
├───────┼────────────────────────────────┼────────────────────────────────────────────────────────────┤
│ FAIL   │ REQUIRED_FIELD_ADDED_TO_INPUT_OBJECT │ input type `ActivateCardInput`: required field `activationCode` added │
```

It looks like schema-check treated the 3 changes to the input as separate changes instead of the the input type creation as a whole.

**Comment by timbotnik** [comment]
👋  Hi @mozhde-amiri thanks for the report.  We've verified this is a bug in that the check is considering the behavior of `REQUIRED_FIELD_ADDED_TO_INPUT_OBJECT` but not taking into account that it is on a new type.  We're working on a fix, stay tuned.

**Comment by nguilford** [comment]
Running into this as well.

**Comment by mohamedjkr** [comment]
@timbotnik we are having the same issue as well, `REQUIRED_FIELD_ADDED_TO_INPUT_OBJECT` causes the subgraph schema check to fail even if there is no recorded operation traffic to check against.

![Github Actions Log Screen](https://user-images.githubusercontent.com/92732053/199699071-b5a3c7a2-0dbf-40db-a62b-9712f336d9e4.jpg)

**Comment by bpuckhaber** [comment]
Hi @mozhde-amiri! A fix has since been deployed which should resolve this issue. Adding the input and mutation from your original post should yield only the two changes below. Could you please verify the fix? Thanks again for raising this issue!

```graphql
input ActivateCardInput {
  cardId: String!
  activationCode: String!
}

extend type Mutation {
  activateCard(input: ActivateCardInput!): Boolean!
}
```

```plaintext
Check Result:

Compared 2 schema changes against 0 operations
┌────────┬─────────────┬─────────────────────────────────────────────┐
│ Change │    Code     │                 Description                 │
├────────┼─────────────┼─────────────────────────────────────────────┤
│ PASS   │ TYPE_ADDED  │ type `ActivateCardInput`: created           │
├────────┼─────────────┼─────────────────────────────────────────────┤
│ PASS   │ FIELD_ADDED │ type `Mutation`: field `activateCard` added │
└────────┴─────────────┴─────────────────────────────────────────────┘
```

cc: @nguilford @mohamedjkr

**Comment by mohamedjkr** [comment]
@bpuckhaber I can confirm this issue has been fixed and our subgraph checks are now passing. Thank you very much!
