### ISSUE TITLE
Shared headers are not included in introspection query

### ISSUE THREAD

**Issue by edokan** [apollographql/apollo-studio-community#230]
Hello,

I have some shared headers defined in "Connection Settings" dialog, but they are sent along the introspection query. Our implementation requires some headers to be present for introspection. Is it possible to send them with introspection query?

probably related to #122

**Comment by mayakoneval** [comment]
Hi @edokan, thanks for the report. 

If you have shared headers defined in the "Connection Settings" dialog they should be sent with your introspection queries. 

Are you seeing different behavior than this? Are your headers requiring environment variables that are not sent?

Thank you, 
Maya

**Comment by edokan** [comment]
@mayakoneval , it seems the problem is related to something else, and Studio, in fact, sends the shared headers with the request. Apologies. For those who will read this in the future, our server returns an incomplete schema, one type is missing to be exact, so the client could not parse it.
