### ISSUE TITLE
Schema Check incorrectly says argument is 'required' when it has a default value

### ISSUE THREAD

**Issue by sgarner** [apollographql/apollo-studio-community#247]
## What type of feedback is this?
- [ ] Question
- [ ] Idea
- [x] Bug
- [ ] New example or operation collection

## Context

When changing an argument with a default value from _nullable_ to _non-nullable_, Apollo Studio Schema Checks incorrectly reports that it has changed from _optional_ to _required_.

When an argument has a default value it is always, by definition, optional. Whether it is also nullable is a separate matter; the default value applies when the argument is omitted, whereas nullable determines whether a `null` value can be passed.

As noted in the GraphQL spec:

> [§5.4.2.1](http://spec.graphql.org/June2018/#sec-Required-Arguments): Arguments can be required. An argument is required if the argument type is non‐null and does not have a default value. Otherwise, the argument is optional.

> [§5.6.4](http://spec.graphql.org/June2018/#sec-Input-Object-Required-Fields): Input object fields may be required. Much like a field may have required arguments, an input object may have required fields. An input field is required if it has a non‐null type and does not have a default value. Otherwise, the input object field is optional.

## Example 

In the following example the argument `includeBeta` to the `appReleases` query changed from:

```graphql
includeBeta: Boolean = true
```
to:
```graphql
includeBeta: Boolean! = true
```

Apollo Studio reports:
> argument changed type optional to required

<img width="568" alt="image" src="https://github.com/apollographql/apollo-studio-community/assets/904004/4ecf7d63-f1d3-46be-9a9b-9380d2b006cf">

In this example it may still be appropriate that Schema Checks reports this as a breaking change, because clients will no longer be able to pass `null` as the value for `includeBeta`. 

It's not correct to say the argument is now "required" however. It remains optional; both before and after the change, if clients omit the argument it will be given the default value `true`.

**Comment by bonnici** [comment]
This has been fixed. We now show what the old type was and what the new type is instead of just saying it changed type.

![SCR-20240404-jrmp](https://github.com/apollographql/apollo-studio-community/assets/1110099/7d1ff288-cd6f-476f-adc2-6796b8b761bf)
