### ISSUE TITLE
Endpoint URL Explorer

### ISSUE THREAD

**Issue by Lishenga** [apollographql/apollo-studio-community#26]
Am new to Apollo Studio and GraphQL, am stuck on explorer and i have already registered my schema on Apollo Studio. To cut the long story short, what is the ENDPOINT URL on Explorer? What does it do and which url am i supposed to provide as the value for the ENDPOINT URL input field?

**Comment by daniman** [comment]
Hi! Great question –– this would be the URL to your actively running server if you want to writes queries in the Explorer and run them against your server to get your data back. The URL could be anything from `http://localhost:4000` to `https://api.github.com/graphql`.

Does that help?

**Comment by Lishenga** [comment]
Hello how can this url be a localhost url because when i input localhost it alerts me with error that the server couldn't be reached

**Comment by daniman** [comment]
Hey @Lishenga –– could you share more information about the error you're seeing? Is there anything being printed to the console?
