### ISSUE TITLE
Inconsistent UI experience on the Subgraphs section in Studio

### ISSUE THREAD

**Issue by FineAndDanD** [apollographql/apollo-studio-community#266]
## Context
When someone has a subgraph uploaded to studio then under the subgraph section they have a button to "Add a Subgraph". When there are no subgraphs that button doesn't exist. This leads to an inconsistent experience and it can be confusing to a consumer. It would be nice if that button was just always there.

No subgraphs:
![スクリーンショット 2023-12-21 18 13 23 (1)](https://github.com/apollographql/apollo-studio-community/assets/149400857/ad23151a-d0fe-42fc-b07e-a90482622046)

One subgraph:
![Screenshot 2023-12-22 at 7 02 39 AM](https://github.com/apollographql/apollo-studio-community/assets/149400857/93619355-2208-4a58-b8fb-54e63595a67d)

## What type of feedback is this?
- [ ] Question
- [ ] Idea
- [X] Bug
- [ ] New example or operation collection

Not sure if it's intended or not but I'm marking it as a bug.

## Is there anything else you'd like to share about the Platform API?
N/A

**Comment by cheapsteak** [comment]
Thanks for the feedback, and much appreciate the screenshots! Just released a fix for this, let us know if you still see it :)

**Comment by FineAndDanD** [comment]
Thanks @cheapsteak! I've confirmed it's working as expected now :)
