### ISSUE TITLE
Wieird Typing BUG on the variable area.

### ISSUE THREAD

**Issue by Allakazan** [apollographql/apollo-studio-community#284]
It's kinda hard to explain, but on the JSON variable area, the text cursor don't represent the actual typing position

Example: 

my cursor is after the number 4.
![image](https://github.com/user-attachments/assets/000651fc-83a3-4ea9-8cc6-bf320799e7e9)

but if i press the backspace

the comma is deleted, and the cursor goes to the number 3. 
![image](https://github.com/user-attachments/assets/199d0000-f33b-4f74-a290-b2766e2a93d3)

i think is an offset problem

**Comment by Allakazan** [comment]
Actually this bug affects all the places where JSON is displayed

I selected the whole line, but it keeps the last word out
![image](https://github.com/user-attachments/assets/07faf977-2c9d-415f-8061-6d85a56448b7)

**Comment by nomiddlename** [comment]
I've seen the same thing, makes the explorer very difficult to use. Only happened with the recent update, I think - was working fine until today.

**Comment by rutek** [comment]
The problem may be related to scaling, as it occurs for me when using default Windows scaling for 2K display (125%), but it works properly when I additionally scale it up in the browser from 100% to 110%.

**Comment by Allakazan** [comment]
> The problem may be related to scaling, as it occurs for me when using default Windows scaling for 2K display (125%), but it works properly when I additionally scale it up in the browser from 100% to 110%.
> 
> System: Chrome 127.0.6533.100 @ Windows 11 Resolution: 2K @ 125% scaling (system level)

Wow. It worked for me too. Crazy.

**Comment by nomiddlename** [comment]
Same here, scaling using browser zoom to either 110% or 90% fixes the problem.

**Comment by Allakazan** [comment]
I think they finally fixed it ! Thanks !
