### ISSUE TITLE
Stuck setting up development graph

### ISSUE THREAD

**Issue by Obversity** [apollographql/apollo-studio-community#43]
As per [this blog post](https://www.apollographql.com/blog/apollo-studio-a-graphql-ide-for-every-environment/) I'm attempting to set up a development graph in Apollo Studio. 

When plugging in my local URL, all I get is this: 

![image](https://user-images.githubusercontent.com/7999019/101733919-7ba6a880-3b0f-11eb-9d5d-ca9b606b8b1a.png)

At first I think I got stuck with CORS issues. I believe I've solved them, but it's still not working, and ~~I assume~~ it's because the API is behind authentication, but I haven't found any way to set authentication headers before setting up the graph. Authentication is required to determine who the client is and what data they have access to, so it's not something that can simply be turned off in development.

**Comment by Obversity** [comment]
So if I change the API to just automatically authenticate for a random client in development mode it works! So I've confirmed it's the authentication issue. Is there any plan to let users specify headers when setting up the graph? (I currently use GraphiQL which supports this.)

Separate question: is there any plan to support markdown in the documentation? Again, this is something GraphiQL supports, so lots of our documentation has markdown. 

Definitely not a convert yet, but I do love certain things about it! The query building is excellent. One of my main gripes with GraphiQL is that there's no easy way to turn your simple `{ something(id: "123") { name } }` query into a parameterized query with variables, and Apollo Studio encourages that from the start.

**Comment by ndintenfass** [comment]
This is on our radar. You are not alone, and we are looking at nicer ways to allow auth headers at setup.

**Comment by Obversity** [comment]
Thanks @ndintenfass , good to know!
