### ISSUE TITLE
Lots of schema introspection requests

### ISSUE THREAD

**Issue by borekb** [apollographql/apollo-studio-community#44]
I'm trying out [Dev Graphs](https://twitter.com/apollographql/status/1336327273943724041) in Apollo Studio and my GraphQL endpoint receive **hundreds** of schema introspection requests (`query IntrospectionQuery`) per minute. My laptop fans are not fans 😄.

**Comment by ndintenfass** [comment]
This is the mechanism used to keep it up to date. You can turn off polling by clicking the box that says "Dev Graph" in the top bar. (It should poll once a second when it's on).

**Comment by borekb** [comment]
Ah sorry, those are requests to "graphql" but I didn't notice the full URL – it's `https://graphql.api.apollographql.com/api/graphql`. That produces a lot more than 1 req/s but at least it's not my endpoint 😄.

<img width="817" alt="Screen Shot 2020-12-11 at 8 56 18" src="https://user-images.githubusercontent.com/101152/101877737-ca475780-3b8e-11eb-92c6-64a50f78bc47.png">
