### ISSUE TITLE
Save query/mutations into curated library

### ISSUE THREAD

**Issue by nebbles** [apollographql/apollo-studio-community#49]
Just been giving the Studio a go for the first time. Having spent most of my time in GraphQL Playground, I am **loving** Apollo Studio already. I would love to switch to it completely, at least to start with for the dev graphs feature before getting our production schema into Studio too.

The _one_ thing that I find though I don't think I could live without is the ability to save queries and mutations into a sort of library. In GraphQL Playground, the closest way of doing this is to just keep the tabs open, and they stay saved.

The `Run History` tab is pretty awesome, however, it contains a full history, whereas I'd like to curate and keep a set of preprepared queries. Another tab alongside the history for saved queries would be ace.

LMK. Many thanks for an awesome GraphQL ecosystem

**Comment by daniman** [comment]
Hi @nebbles! I couldn't agree more, and this has been high on my personal wish list for a while. I hope we're able to get it in the next few months! In the meantime, I've just been keeping lots of operations in my Explorer editor at the same time. The editor is able to handle multiple operations fine without losing context.

**Comment by nebbles** [comment]
Thanks! Great news - looking forward to it 😄 just as an extension, this would also be super valuable to be able to share with the rest of the org/team too!

**Comment by daniman** [comment]
(sorry for the delay, missed the notification!)

@nebbles absolutely. There's actually already a button to share things one-off in the "..." menu next to each of your operations in the Explorer. It says "copy link to operation". I use that all the time to link my teammates to operations I'm working on, it's easily one of my favorite features.

**Comment by nebbles** [comment]
@daniman that link feature is definitely very handy, although I'm a little scared of it since I've already had once situation where I tried plugging it in the URL myself to see what happened and it indeed showed me that query but also cleared all my other cached queries from my explorer. 

My cache also got cleared at another point for some reason unknown, hence super looking forward to being able to specifically save them!

**Comment by daniman** [comment]
@nebbles yeah that has very much happened for me as well, though I've been able to use the History tab to recover the previous state of the Editor, so it at least wasn't entirely lost 😅

**Comment by joelhoelting** [comment]
@daniman Can we please have a status update on this?

**Comment by daniman** [comment]
Hey @joelhoelting! We actually [opened a preview doc for operation collections](https://github.com/apollographql/apollo-studio-community/blob/main/preview-docs/OperationsCatalog.md) earlier this month if you'd like to take a look –– would love to hear your feedback. We're currently planning on building this out later this year, though we're still in the feedback gathering and planning stage.

And even though this isn't quite the same thing... we're planning to roll out tabs in the Explorer later this week :) Hopefully that'll be helpful to you too. It's something that a lot of folks have asked for consistently.

**Comment by setchy** [comment]
We can't wait for the `tabs` feature to roll-out.  That'll help our engineers make the transition from Playground

Also very excited for the `Operations Collections` feature set too.  😍 all those use-cases

**Comment by papollosc** [comment]
Thank you @setchy and @bombillazo !! We are in the process of building operation collections in Explorer. Coming soon! 🚀

**Comment by papollosc** [comment]
Hi @bombillazo! Wanted to give you an update here. We have rolled out Operation Collections feature in Explorer that allows you to save queries and mutations as folders. Please do check it out and let us know if you have any feedback. Here is the [blogpost](https://www.apollographql.com/blog/announcement/platform/save-and-share-your-graphql-operations-in-apollo-explorer/) 🚀 

I will close this ticket for now and please open any new issues/discussions with further feedback. Thank you so much.
