### ISSUE TITLE
Query builder doesn't support more than one operation and fragments

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [apollographql/apollo-studio-community#5]
How to reproduce?

1. Paste the following into the code panel:

```graphql
query Query1 {
  me {
    id
  }
}

query Query2 {
  me {
    ...UserFields
  }
}

fragment UserFields on User {
  name
  username
}
```

2. Try to modify the `Query2` query or `UserFields` fragment using query builder panel (not code panel).

My vision is query builder is just another (visual) one-to-one representation of code. And everything that could be possible via code should be possible via query builder, and vice versa. I think the main goal of query builder is that it allows users to build full GraphQL queries without typing a single line of code.

There are some pain points for new GraphQL users. Specifically [union types and inline fragments](https://graphql.org/learn/queries/#inline-fragments). If the user is not aware of this syntax to query this type of fields it can be a fairly frustrating experience! Query builder helps solve these problems.

Multi-operation and fragments are supported in GraphiQL Explorer. See:

* https://www.onegraph.com/blog/2019/05/30/GraphiQL_Explorer_2_0_A_Power_User_Release.html#multi-operation-support

* https://youtu.be/yWjCAjpHRt0

**Comment by FluorescentHallucinogen** [comment]
Re search. If multiple operation support will be added, will have to reconsider how search works. Currently, spotlight search works globally, and as long as we have only one operation, this works. If we have more than one operations, we will need to have a search for each of them. Otherwise, how do we understand in which operation we should add the found field?

Something like this:

![graphql-multi-operation-search](https://user-images.githubusercontent.com/7892779/71314182-d48bb580-2454-11ea-88e1-d99443f88435.png)

Pay attention to the search field in each operation.

Pay attention to the "Add new query", "Add new mutation" and "Add new subscription" buttons.

**Comment by daniman** [comment]
@FluorescentHallucinogen we've fixed a lot of bugs in the last few weeks, and I think this does actually work the way you want it to now. The trick to managing multiple queries with both the search and docs query building is to focus your cursor on the query you want to be adding to. Whenever you click the (+) button, your field will be adding to whichever query your cursor is focused on.

**Comment by FluorescentHallucinogen** [comment]
@daniman But what about fragments?
