### ISSUE TITLE
Error (/newService): Transient error

### ISSUE THREAD

**Issue by Lostbrokenkey** [apollographql/apollo-studio-community#57]
I keep getting this error:

<a href="https://ibb.co/d0S7qBW"><img src="https://i.ibb.co/Z63NPdL/apollo-error.png" alt="apollo-error" border="0"></a>

**Comment by daniman** [comment]
Hi @Lostbrokenkey! Thanks so much for opening this issue. We identified the source and have released a fix, so you should be good to go now: https://status.apollographql.com/incidents/m1cdgzz1jrrx.
