### ISSUE TITLE
Question about the schema registry

### ISSUE THREAD

**Issue by MM3y3r** [apollographql/apollo-studio-community#59]
In my project, we have several Graphql APIs that have their schema stitched into one larger schema on startup. We were hoping to use the schema registry feature as a single source of truth for these services during and after db migrations. It was quite easy to integrate with our CLI regarding the upload of the schema.

Is it also possible to download the schema from the registry? We could not find that feature.

**Comment by ndintenfass** [comment]
Yes, you can. I'd suggest checking out the public preview of our new CLI, which has commands built in to fetch schema: https://github.com/apollographql/rover

**Comment by MM3y3r** [comment]
> Yes, you can. I'd suggest checking out the public preview of our new CLI, which has commands built in to fetch schema: https://github.com/apollographql/rover

Thanks for the quick answer! I'll check it out.
