### ISSUE TITLE
Extra scrollbar

### ISSUE THREAD

**Issue by fabien0102** [apollographql/apollo-studio-community#6]
Hello,

First of all, amazing product! Very nice to use 👌 

Just a tiny bug to make it even better (easier to spot on windows since mac hide the scrollbar by default), you have an extra scrollbar in the main layout

![image](https://user-images.githubusercontent.com/1761469/86469051-ebcb2a00-bd38-11ea-95a2-4716178eb785.png)
![image](https://user-images.githubusercontent.com/1761469/86469167-29c84e00-bd39-11ea-8ba1-0860a69998b1.png)

**Comment by daniman** [comment]
Thanks @fabien0102! We'll get this fixed :)

**Comment by daniman** [comment]
@fabien0102 I think we've fixed this –– would you mind checking on your side? :)

**Comment by fabien0102** [comment]
@daniman Perfect 👌 
![image](https://user-images.githubusercontent.com/1761469/86829587-de91a080-c094-11ea-8b6f-d66217a67dba.png)
