### ISSUE TITLE
Content Header Missing From Generated Curl Code

### ISSUE THREAD

**Issue by conradwt** [apollographql/apollo-studio-community#73]
When copying the **curl code** from the Apollo Studio, I'm getting the following:

```text
curl --request POST \
    --url http://localhost:4000/graphiql \
    --data '{"query":"query ExampleQuery($personId: ID!) {\n  person(id: $personId) {\n    email\n  }\n}","variables":"{\n  \"personId\": \"1\"\n}"}'
```

but it needs to be the following in my local development environment:

```text
curl -i --request POST \
 --url http://localhost:4000/graphiql \
 -H "Content-Type: application/json" \
 --data '{"query":"query ExampleQuery($personId: ID!) {\n person(id: $personId) {\n email\n }\n}","variables":"{\n \"personId\": \"1\"\n}"}' 
```

This may or may not be an issue but the content header `-H "Content-Type: application/json"` is missing in the curl code.

**Comment by daniman** [comment]
Hey @conradwt, we added this last year shortly after you requested it, so I'm going to close this issue now 😄  Sorry for not following up back then!
