### ISSUE TITLE
Response Header in Apollo Studio incomplete compared to in chrome developer tools network

### ISSUE THREAD

**Issue by longility** [apollographql/apollo-studio-community#89]
I'm expecting the response header in apollo studio to match response header in chrome developer tools. However, they are not the same.

Response header in Apollo Studio:
![image](https://user-images.githubusercontent.com/720635/123531592-797ef280-d6cb-11eb-9cb6-7795560b68b3.png)

Response header in Chrome developer tools network:
![image](https://user-images.githubusercontent.com/720635/123531614-a16e5600-d6cb-11eb-9024-73cad7958b8a.png)

**Comment by cheapsteak** [comment]
Thanks so much for the heads up!  

It looks like we'll need to add some messaging for why only a portion of the headers are visible

If you're able to, you could set Access-Control-Expose-Headers on the endpoint to expose more headers to the app

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

**Comment by longility** [comment]
@cheapsteak ,

Your suggestion of adding `Access-Control-Expose-Headers` actually did the trick.

![image](https://user-images.githubusercontent.com/720635/123673770-79374200-d806-11eb-943c-697dc6ab1fc4.png)

Not sure if you want to document, make more automatic, or what not, but at least this will help me to where I'm comfortable closing this issue.

**Comment by longility** [comment]
For anyone else out there, this is a shortened version of my context.

```typescript
export const context = async ({
  req,
  res,
}: {
  req: express.Request;
  res: express.Response;
}): Promise<ServerContext> => {
    const traceresponse = "foo";

    res.header("traceresponse", traceresponse);
    res.header("Access-Control-Expose-Headers", "traceresponse");
  }

  return {};
};
```

**Comment by cheapsteak** [comment]
Just merged a PR to add a link to the MDN doc for Access-Control-Expose-Headers in the headers pane!

Thanks again for raising, and for adding sample code 🙏  gonna close then :)
