### ISSUE TITLE
Suggestions in Variables stopped working

### ISSUE THREAD

**Issue by enorenio** [apollographql/apollo-studio-community#96]
I am using ApolloServer with express and the schema is being created via Nexus' `makeSchema()`
From the start of the project the suggestions was working, but then at some point they just stopped working.

Attached the image:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/31052466/130444904-b27c3482-efde-4a6f-84d9-091d0e4fb3e1.png">

**Comment by papollosc** [comment]
Thank you @enorenio for raising this issue! We are in the process of addressing it. Will let you know once it has been!

**Comment by jgzuke** [comment]
@enorenio sorry for the trouble! This should be fixed now 😄
