### ISSUE TITLE
Support for graphql-ws?

### ISSUE THREAD

**Issue by NanddoSalas** [apollographql/apollo-studio-community#97]

**Comment by jjangga0214** [comment]
Note: [Altair](https://altair.sirmuel.design/) supports it.
![Screenshot from 2021-10-04 16-51-51](https://user-images.githubusercontent.com/28584151/135813635-0ee78d8a-59e1-4d97-83fd-caa7bc6d7c87.png)

**Comment by NanddoSalas** [comment]
## Apollo Studio now supports `graphql-ws` protocol (well done).
![apollo](https://user-images.githubusercontent.com/41311861/149399828-7a46ff32-c00e-4b8a-a3dd-8830bd903caf.png)
